language: 'go'
go:
  - '1.10'

install:
  - 'curl -L https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 > $GOPATH/bin/dep'
  - 'chmod +x $GOPATH/bin/dep'
  - 'dep ensure -v'

script:
  - 'go test -v ./...'
